### ISSUE TITLE
Python Crashes with gta.load_roi

### ISSUE THREAD

**Issue by bkapanadze1976** [fermiPy/fermipy#483]
Hi,
I tried to construct  a LAT-band SED of Markarian 421 using Fermipy-1.1.4 installed along with Fermitools-2.2.0 (Ubuntu 22.04). Everything OK till the command gta.load_roi which yields a Python crash and appearing the error message as follows:

INFO    GTAnalysis.load_roi(): Loading ROI file: /home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/fermipy/initial.npy
INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
Segmentation fault (core dumped)

Your suggestions, please?

**Comment by henrikef** [comment]
Could you share your config file, script or notebook, and any output you get before the crash, please? 

Also, here are some things to test (on the command line, inside your `fermi-2.2.0` environment):

* `fermitools`: Run the command `test_Likelihood`. Post the output here.
* `fermipy`: First, install `pytest` if you don't have it yet: `pip install pytest`. Then create a new directory for temp files, enter that directory, and run `pytest --pyargs fermipy`. Post the output here.

**Comment by bkapanadze1976** [comment]
Hi,

See the attached files.

Regards,
Dr. Associate Professor Bidzina Kapanadze,
Abastumani Astrophysical Observatory,
Ilia State University, Tbilisi, Georgia
INAF-OAB, Merate, Italy
Tel: +995 577413299

**Comment by henrikef** [comment]
I'm sorry but I don't see any files.

**Comment by bkapanadze1976** [comment]
What about the files attached to my previous mail?

Regards,
Dr. Associate Professor Bidzina Kapanadze,
Abastumani Astrophysical Observatory,
Ilia State University, Tbilisi, Georgia
INAF-OAB, Merate, Italy
Tel: +995 577413299

**Comment by bkapanadze1976** [comment]
Hi,

According to your suggestions, I acted as follows:
1. conda activate fermi-2.2.0
    test_Likelihood >& test_Likelihood.log
2. -installed pytest
    - created folder Pytest
cd Pytest
pytest --pyargs fermipy

The files generated during these actions are provided to you. Is everything
done correctly?

The screen output during the last command was as follows:
============================ test session starts
==============================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/bk/pytest
collected 84 items


diffuse/tests/test_binning.py .                                          [
 1%]
diffuse/tests/test_link_classes.py .....                                 [
 7%]
diffuse/tests/test_managers.py ....                                      [
11%]
diffuse/tests/test_name_factory.py .                                     [
13%]
diffuse/tests/test_spectral.py .                                         [
14%]
jobs/tests/test_analysis.py ..                                           [
16%]
jobs/tests/test_chain.py ..                                              [
19%]
jobs/tests/test_collect.py ..                                            [
21%]
jobs/tests/test_file_archive.py ..                                       [
23%]
jobs/tests/test_gtlink.py .                                              [
25%]
jobs/tests/test_job_archive.py ..                                        [
27%]
jobs/tests/test_plotting.py ..                                           [
29%]
jobs/tests/test_sim.py ..                                                [
32%]
tests/test_castro.py .x..                                                [
36%]
tests/test_config.py ....                                                [
41%]
tests/test_gtanalysis.py .......s.s......                                [
60%]
tests/test_irfs.py ......                                                [
67%]
tests/test_roi_model.py ..................                               [
89%]
tests/test_sensitivity.py ...                                            [
92%]
tests/test_skymap.py ..                                                  [
95%]
tests/test_spectrum.py ....
 [100%]

=============================== warnings summary
===============================
../anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/gammapy/maps/region/ndmap.py:3

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/gammapy/maps/region/ndmap.py:3:
DeprecationWarning: Please use `label` from the `scipy.ndimage` namespace,
the `scipy.ndimage.measurements` namespace is deprecated.
    from scipy.ndimage.measurements import label as ndi_label

tests/test_gtanalysis.py::test_gtanalysis_setup

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/astropy/wcs/wcs.py:725:
FITSFixedWarning: 'datfix' made the change 'Set DATEREF to
'2001-01-01T00:01:04.184' from MJDREF.
  Set MJD-OBS to 54682.655283 from DATE-OBS.
  Set MJD-END to 56874.155007 from DATE-END'.
    warnings.warn(

tests/test_gtanalysis.py::test_gtanalysis_write_roi
tests/test_gtanalysis.py::test_gtanalysis_write_roi

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/astropy/io/fits/column.py:2646:
AstropyUserWarning: Format %s cannot be mapped to the accepted TDISPn
keyword values.  Format will not be moved into TDISPn keyword.
    warnings.warn('Format {} cannot be mapped to the accepted '

tests/test_gtanalysis.py::test_gtanalysis_write_roi

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/astropy/io/fits/column.py:2646:
AstropyUserWarning: Format %f cannot be mapped to the accepted TDISPn
keyword values.  Format will not be moved into TDISPn keyword.
    warnings.warn('Format {} cannot be mapped to the accepted '

tests/test_gtanalysis.py::test_gtanalysis_optimize
tests/test_gtanalysis.py::test_gtanalysis_find_sources

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/scipy/interpolate/_fitpack2.py:280:
UserWarning:
  The maximal number of iterations maxit (set to 20 by the program)
  allowed for finding a smoothing spline with fp=s has been reached: s
  too small.
  There is an approximation returned but the corresponding weighted sum
  of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
    warnings.warn(message)

tests/test_gtanalysis.py::test_gtanalysis_extension_gaussian

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/fermipy/tsmap.py:433:
RuntimeWarning: invalid value encountered in double_scalars
    delta = grad / hess

tests/test_gtanalysis.py::test_gtanalysis_lightcurve

/home/bk/anaconda3/envs/fermi-2.2.0/lib/python3.9/site-packages/astropy/wcs/wcs.py:725:
FITSFixedWarning: 'datfix' made the change 'Set DATEREF to
'2001-01-01T00:01:04.184' from MJDREF.
  Set MJD-OBS to 54682.655283 from DATE-OBS.
  Set MJD-END to 54884.199977 from DATE-END'.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======= 81 passed, 2 skipped, 1 xfailed, 9 warnings in 224.69s (0:03:44)
=======

Dr. Associate Professor Bidzina Kapanadze,
Abastumani Astrophysical Observatory,
Ilia State University, Tbilisi, Georgia
INAF-OAB, Merate, Italy
Tel: +995 577413299

**Comment by henrikef** [comment]
The tests pass, that's good news and means most likely `fermipy` is working correctly.

I still cannot see any attachments. Did you try to attach any files to this issue?

To try and reproduce the issue I would need your configuration file and your script or notebook.
